# Generated by Django 5.1 on 2024-09-12 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_tracker', '0002_project_task_user_attachment_comment_task_project_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='attachment',
            table='attachment',
        ),
        migrations.AlterModelTable(
            name='comment',
            table='comment',
        ),
        migrations.AlterModelTable(
            name='project',
            table='project',
        ),
        migrations.AlterModelTable(
            name='tag',
            table='tag',
        ),
    ]
