# Generated by Django 5.1 on 2024-09-19 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_tracker', '0003_alter_attachment_table_alter_comment_table_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'задачи', 'verbose_name_plural': 'задачи'},
        ),
        migrations.AddField(
            model_name='task',
            name='photo',
            field=models.ImageField(null=True, upload_to='tasks'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(max_length=256, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='task',
            name='height_level',
            field=models.PositiveIntegerField(null=True, verbose_name='уровень сложности'),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('h', 'High'), ('m', 'Medium'), ('l', 'Low')], max_length=2, null=True, verbose_name='приоритет'),
        ),
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='task_tracker.project', verbose_name='проект'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('op', 'Open'), ('cl', 'Close'), ('pr', 'Process')], max_length=2, null=True, verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=64, verbose_name='заголовок'),
        ),
        migrations.AlterField(
            model_name='task',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
    ]
